//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCJ.OA.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Articel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articel()
        {
            this.ArticelComment = new HashSet<ArticelComment>();
            this.ArticelClass = new HashSet<ArticelClass>();
        }
    
        public int ID { get; set; }
        public string KeyWords { get; set; }
        public string TitleType { get; set; }
        public string Title { get; set; }
        public string FullTitle { get; set; }
        public string Intro { get; set; }
        public string TitleFontColor { get; set; }
        public string TitleFontType { get; set; }
        public string ArticleContent { get; set; }
        public string Author { get; set; }
        public string Origin { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public short DelFlag { get; set; }
        public short PicNews { get; set; }
        public short Changes { get; set; }
        public short Recommend { get; set; }
        public short Rolls { get; set; }
        public short Strip { get; set; }
        public short Popular { get; set; }
        public short Verific { get; set; }
        public short IsTop { get; set; }
        public int CommnetNum { get; set; }
        public string PhotoUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<ArticelComment> ArticelComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<ArticelClass> ArticelClass { get; set; }
    }
}
