//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCJ.OA.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ArticelComment
    {
        public int ID { get; set; }
        public string Msg { get; set; }
        public System.DateTime AddDate { get; set; }
        public short IsPass { get; set; }
        public int ArticelID { get; set; }
    
        [JsonIgnore]
        public virtual Articel Articel { get; set; }
    }
}
