//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCJ.OA.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SensitiveWord
    {
        public int ID { get; set; }
        public string WordPattern { get; set; }
        public bool IsForbid { get; set; }
        public bool IsMod { get; set; }
        public string ReplaceWord { get; set; }
    }
}
